version: '3.8'

services:
  paradigm-ui:
    ports:
        - 3000:3000
    build: # "context" and "dockerfile" fields have to be under "build"
      context: .
      dockerfile: paradigm-ui/Dockerfile
      network: host
    networks:
        - paradigm

  paradigm:
    ports:
        - 5000:5000
    build: # "context" and "dockerfile" fields have to be under "build"
      context: .
      dockerfile: src/Dockerfile
      network: host
    networks:
        - paradigm

networks:
  paradigm:
